import { useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { UserPlus } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { Gender, PaymentStatus, NursePatient } from '../types'
import { nextCardNumber, addPatient } from '../store'
import PatientCardModal from './PatientCardModal'
import { queueApi } from '../../../../lib/api'

interface Props { onDone: () => void }

const SERVICES = ['Cleaning', 'Whitening', 'Extraction', 'Braces', 'Surgery', 'Consultation', 'X-Ray']

/** Rough estimate: 8 minutes per patient ahead in the queue */
const EST_SECONDS_PER_PATIENT = 8 * 60

export default function RegisterPatient({ onDone }: Props) {
  const { t } = useTranslation()
  const [registeredPatient, setRegisteredPatient] = useState<NursePatient | null>(null)
  const [loading, setLoading] = useState(false)
  const [apiError, setApiError] = useState('')
  const [form, setForm] = useState({
    fullName: '', age: '', gender: 'Male' as Gender,
    phone: '', email: '', telegramId: '',
    address: '', emergencyContact: '',
    visitDate: new Date().toISOString().slice(0, 10),
    cardFee: '200', serviceType: 'Cleaning',
    paymentStatus: 'Paid' as PaymentStatus,
  })

  function set(k: string, v: string) { setForm(f => ({ ...f, [k]: v })) }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setApiError('')

    const now = new Date()
    const patient: NursePatient = {
      id: Date.now().toString(),
      cardNumber: nextCardNumber(),
      fullName: form.fullName,
      age: Number(form.age),
      gender: form.gender,
      phone: form.phone,
      email: form.email,
      telegramId: form.telegramId,
      address: form.address,
      emergencyContact: form.emergencyContact,
      visitDate: form.visitDate,
      cardFee: Number(form.cardFee),
      paymentStatus: form.paymentStatus,
      waitingStatus: 'Waiting',
      registeredAt: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      serviceType: form.serviceType,
    }

    // Save locally (in-memory store for the nurse dashboard)
    addPatient(patient)

    // Also add to the live public queue in Supabase.
    // We fire this as a best-effort — a failure here won't block the registration.
    try {
      await queueApi.add({
        patient_name: patient.fullName,
        treatment: patient.serviceType,
        // Rough estimate based on how many patients are already waiting.
        // The backend will assign the real queue_number.
        est_wait_seconds: EST_SECONDS_PER_PATIENT,
      })
    } catch (err) {
      // Non-blocking: log but don't stop the nurse flow
      console.warn('[RegisterPatient] queue API error:', err)
    }

    setLoading(false)
    setRegisteredPatient(patient)
  }

  return (
    <>
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }}>
        <div className="bg-white rounded-2xl border border-slate-100 p-6 max-w-2xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-9 h-9 rounded-xl bg-cyan-50 border border-cyan-100 flex items-center justify-center">
              <UserPlus className="w-4 h-4 text-cyan-600" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-[#0d2044] uppercase tracking-widest">{t('nurse.registerNew')}</h2>
              <p className="text-[11px] text-slate-400">{t('nurse.cardAutoGenerated')}</p>
            </div>
          </div>

          {apiError && (
            <div className="mb-4 rounded-xl bg-red-50 border border-red-100 px-4 py-2.5 text-xs text-red-600">
              {apiError}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Field label={t('nurse.fullName')}         value={form.fullName}         onChange={v => set('fullName', v)}         required />
              <Field label={t('nurse.age')}              value={form.age}              onChange={v => set('age', v)}              type="number" required />

              <div>
                <label className="field-label">{t('nurse.gender')}</label>
                <select value={form.gender} onChange={e => set('gender', e.target.value)} className="field-input">
                  <option value="Male">{t('nurse.male')}</option>
                  <option value="Female">{t('nurse.female')}</option>
                  <option value="Other">{t('nurse.other')}</option>
                </select>
              </div>

              <Field label={t('nurse.phoneNumber')}      value={form.phone}            onChange={v => set('phone', v)}            required />
              <Field label={t('nurse.emailAddress')}     value={form.email}            onChange={v => set('email', v)}            type="email" />
              <Field label={t('nurse.telegramUsername')} value={form.telegramId}       onChange={v => set('telegramId', v)}       placeholder="@username" />
              <Field label={t('nurse.address')}          value={form.address}          onChange={v => set('address', v)}          required />
              <Field label={t('nurse.emergencyContact')} value={form.emergencyContact} onChange={v => set('emergencyContact', v)} />
              <Field label={t('nurse.visitDate')}        value={form.visitDate}        onChange={v => set('visitDate', v)}        type="date" required />

              <div>
                <label className="field-label">{t('nurse.serviceType')}</label>
                <select value={form.serviceType} onChange={e => set('serviceType', e.target.value)} className="field-input">
                  {SERVICES.map(s => <option key={s}>{s}</option>)}
                </select>
              </div>

              <Field label={t('nurse.cardFee')}          value={form.cardFee}          onChange={v => set('cardFee', v)}          type="number" required />

              <div>
                <label className="field-label">{t('nurse.paymentStatus')}</label>
                <select value={form.paymentStatus} onChange={e => set('paymentStatus', e.target.value as PaymentStatus)} className="field-input">
                  {(['Paid','Partial','Unpaid'] as PaymentStatus[]).map(s => <option key={s}>{s}</option>)}
                </select>
              </div>
            </div>

            <motion.button
              type="submit"
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.98 }}
              disabled={loading}
              className="w-full mt-2 bg-gradient-to-r from-[#0d2044] to-[#0e3a6e] text-white rounded-xl py-3 text-xs font-bold uppercase tracking-widest flex items-center justify-center gap-2 hover:opacity-90 transition-opacity disabled:opacity-60"
            >
              {loading
                ? <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                : <UserPlus className="w-4 h-4" />
              }
              {loading ? t('nurse.generatingCard') : t('nurse.generateCard')}
            </motion.button>
          </form>
        </div>
      </motion.div>

      <AnimatePresence>
        {registeredPatient && (
          <PatientCardModal
            patient={registeredPatient}
            onClose={() => { setRegisteredPatient(null); onDone() }}
          />
        )}
      </AnimatePresence>
    </>
  )
}

function Field({ label, value, onChange, type = 'text', required, placeholder }: {
  label: string; value: string; onChange: (v: string) => void
  type?: string; required?: boolean; placeholder?: string
}) {
  return (
    <div>
      <label className="field-label">{label}</label>
      <input
        type={type} value={value} placeholder={placeholder}
        onChange={e => onChange(e.target.value)}
        required={required} className="field-input"
      />
    </div>
  )
}
